### PR TITLE
Update to work with RSS Atom feed

### PR DESCRIPTION
**Pull request by BladeFireLight**
# Description

the support.microsoft.com RSS Atom feed is kept current, 

## Related Issue

https://github.com/aaronparker/LatestUpdate/issues/17

## Motivation and Context

the JSON feed was not updated and missing at least 2 more recent updates.

## How Has This Been Tested?

Get-LatestUpdate -verbose -WindowsVersion Windows10
Get-LatestUpdate -verbose -WindowsVersion Windows8
Get-LatestUpdate -verbose -WindowsVersion Windows7

gave expected output

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [x] I have updated the CHANGELOG file accordingly for the version that this merge modifies.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronparker** [comment]
Great stuff. Will test this out over the weekend.

**Comment by BladeFireLight** [comment]
what do I need to change to get it to pass checks?

**Comment by aaronparker** [comment]
Will look at this ASAP.

**Comment by ILikeMonad** [comment]
This is not working any more. When i try to run It with the fixes it returns the KB 4464218.

image

**Comment by BladeFireLight** [comment]
Thanks for the head's up. Microsoft has their KB numbers out of order for some reason. 
I could not get your code to work but it pointed me in the right direction. 
It should work for win7/8 again to.

**Comment by ILikeMonad** [comment]
No Problems. I can see why it’s not working. The regex is wrong. The capture group name is missing. 
But good you got it working.

**Comment by BladeFireLight** [comment]
the windows 7/8 code still pulls based on the highest KB, but I see no way to address that.

**Comment by sloth8871** [comment]
Any chance this can also be modified to include monthly flash updates and servicing stack updates? they appear to be in the XML feed  already just need the logic added to enable search and download.

**Comment by BladeFireLight** [comment]
Can you point out what it looks like? I'm not familiar with "Flash Update"

**Pull request merged**
