### PR TITLE
Markup and typo fixes + BitsTransfer priority to default

### PR DESCRIPTION
**Pull request by f0nt4**
I've made some little changes to the markup and fixed a little typo.
The markup changes are purely code readability related and eliminate the use of backticks.

The change in the BitsTranfer priority from High to default (Foreground) in the Save-LatestUpdate function made the experience of downloading the updates feel a lot smoother.
According to the MS documentation on Start-BitsTransfer that makes sense.

image
From: https://docs.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=win10-ps#optional-parameters

Maybe it's an idea to make `-DownloadPriority` a parameter on the Save-LatestUpdate function?

All in all, the module seems to work flawlessly.
image
This is a screenshot of my [Get-Updates](https://github.com/f0nt4/Get-Updates) script at work using your module.

### CODE REVIEW

**Comment by aaronparker** [comment]
You've got `WindowsAll` as the parameter value. Could you please update to make it just `All`?

**Comment by aaronparker** [comment]
I can add the `Priority` parameter to `Save-LatestUpdate`. I was looking at `Get-UpdateCatalogDownloadInfo` today and I need to change the logic slightly.

**Comment by f0nt4** [comment]
Changed it to "All", pulled your changes for Windows Defender in it, and parameterized OS in the different public functions. By doing this, the switch isn't needed anymore in `Get-LatestMonthlyRollup`.

**Comment by f0nt4** [comment]
I've added the `-Priority` parameter. Not sure if you'd want to give it another name though.
Simply "Priority" sounds fine by me 😛 

Preventing `Get-UpdateCatalogDownloadInfo` from spitting out empty objects might be as simple as wrapping the Write-Output in an if-statement:

image

But I can image you'd like to prevent the function from creating an object in the first place when it doesn't meet the wanted criteria.

**Comment by f0nt4** [comment]
Thanks! 😄

**Comment by aaronparker** [comment]
I've backed out the `-OS` parameter on all but `Get-LatestNetFrameworkUpdate`. They weren't working (even though the previous AppVeyor test worked).

Let me take a look at the code again - I want to strike a balance between code complexity and features. The JSON is starting to get a bit big.

**Comment by f0nt4** [comment]
I see what you mean. I'll leave my fork for what it is at this moment.
I added the `-OS` parameter merely so it wasn't hardcoded in the code.

The json indeed got a little bit bigger, that's why I also removed "NetFramework" from the searchstrings so they could be used in general.

**Comment by f0nt4** [comment]
I managed to get the `-OS` parameter to work. Eventually it was "as simple as" adding `-OS $resourceStrings.SearchStrings.$OS` to the `Get-UpdateCatalogDownloadInfo` command.

**Get-LatestAdobeFlashUpdate**
image

**Get-LatestCumulativeUpdate**
image

**Get-LatestMonthlyRollup**
image

**Get-LatestNetFrameworkUpdate** *(Only made a screenshot of the default Windows 10 output)*
image

**Get-LatestServicingStack**
image

**Comment by aaronparker** [comment]
Excellent. I'll take a look as soon as I can.

**Pull request merged**
