### PR TITLE
Added -OS support + Proxy fix

### PR DESCRIPTION
**Pull request by f0nt4**
After creating a new fork, I added back in the `-OS` support and tested it if it works correctly.
As you can see in my last comment in the previous PR, it actually does.

Also today while trying to download the updates I found out that the `-Proxy` param was broken.
This is fixed in this PR.

### CODE REVIEW

**Comment by aaronparker** [comment]
Is there a better parameter name than `OS`?
Should we make this `OperatingSystem` or collapse into `Version`?

The problem with `Get-LatestServicingStackUpdate` for example - is the `-Version 1809` and `-OS Windows8` is valid on the command line and therefore requires filtering to change what the user has specified on the command.

**Comment by aaronparker** [comment]
Is there a better parameter name than `OS`? Should this be `OperatingSystem` instead?

**Comment by f0nt4** [comment]
Good questions and I see what you mean. I'm not sure if it would be a good idea to collapse both parameters into 1. The name of the OS and the version are actually 2 different things. I'm also almost sure that it will give headaches for `Get-LatestCumulativeUpdate` the way that function is currently setup where it actually uses both. But also in the future you might want to have it split.

It might be a lot simpler to do some validation on the Version parameter and throw an error, or ignore the users input and show a warning that it's an invalid combination. 
The latter would follow Jeffrey Snover's proclamation that a script should "Just work".

"Jeffrey Snover, the Windows PowerShell grand architect, wisely proclaims that Windows PowerShell differs from other languages in that scripts should "just work". Windows PowerShell scripts should make the user successful." - Copied from https://powershell.org/2013/05/validatescript-for-beginners/

`Get-LatestServicingStackUpdate` is already ignoring the version if the OS is anything else than Windows10. Which follows this "guideline", but doesn't give a warning.

`OperatingSystem` might indeed be better than `-OS`. Could change it to `OperatingSystem` and give it an alias of "OS" as it's actually the same but just an abbreviation.

**Comment by f0nt4** [comment]
As said, I changed the OS to OperatingSystem, and give a warning when using a wrong combo.

image

**Pull request merged**
